apiVersion: v1
kind: ConfigMap
metadata:
  name: "iatipublisher"
data:
  APP_NAME: "IATI Publisher"
  APP_ENV: "production"
  APP_DEBUG: "false"

  APP_URL: "https://publisher.iatistandard.org"
  APP_TIMEZONE: "UTC"

  DEBUGBAR_ENABLED: "false"

  LOG_CHANNEL: "daily"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "pgsql"
  DB_DATABASE: "iatipublisher_prod"
  DB_HOST: "private-iati-postgresql-prod-do-user-4025190-0.b.db.ondigitalocean.com"
  DB_PORT: "25061"
  DB_SSLMODE: 'require'
  DB_SSLROOTCERT: './ca-certificate.crt'

  AIDSTREAM_DB_HOST: "private-aidstream-postgresql-do-user-4025190-0.b.db.ondigitalocean.com"
  AIDSTREAM_DB_PORT: "25060"
  AIDSTREAM_DB_DATABASE: "aidstream_prod"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "redis"
  FILESYSTEM_DISK: "s3"

  QUEUE_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"

  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  SESSION_SECURE_COOKIE: "true"

  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "tls://private-yi-redis-prod-do-user-4025190-0.b.db.ondigitalocean.com"
  REDIS_USERNAME: "default"
  REDIS_PORT: "25061"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "email-smtp.us-east-1.amazonaws.com"
  MAIL_PORT: "587"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "support@iatistandard.org"
  MAIL_FROM_NAME: "IATI Publisher"

  IATI_VALIDATOR_ENDPOINT: "https://api.iatistandard.org/validator/validate"

  IATI_API_ENDPOINT: "https://iatiregistry.org/api"

  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: "iatipublisher-prod"
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  CSV_DATA_STORAGE_PATH :  'CsvImporter/tmp'
  CSV_FILE_STORAGE_PATH :  'CsvImporter/file'
  XML_DATA_STORAGE_PATH :  'XmlImporter/tmp'
  XML_FILE_STORAGE_PATH :  'XmlImporter/file'

  SENTRY_LARAVEL_DSN: "https://c4ba35dbbb854aa78db042552d692104@o4504553711796224.ingest.sentry.io/4504553729359872"
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
