# This is a basic workflow to help you get started with Actions

name: Production Deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Production Deploy
        # You may pin to the exact commit or the version.
        # uses: AlexxNB/caprover-action@45fdf55f3213582285394908e8a3a0d2df41e21d
        uses: AlexxNB/caprover-action@v1
        with:
          # CapRover admin panel URL. Ex. https://captain.root.domain.com
          server: 'https://captain.caprover.staging.yipl.com.np'
          # CapRover admin password. Use $\{{ secrets.CAPROVER_PASSWORD }} for better security.
          password: ${{ secrets.CAPROVER_PASSWORD }}
          # Application name on the CapRover server. Must exists.
          appname: 'iatipublisher-prod'
          # Branch which will be deployed
          branch: main
